os: osx
osx_image: xcode11.1
language: swift
branches:
  only:
  - "/^develop\\/.*$/"
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROFILE_NAME="JP_Performance_App_Store"
  - PROFILE_NAME_ADHOC="JP_Performance_Ad_Hoc"
  - secure: aqmKhr4uXejX8/jtjWuCXFSgMTrelofyvP+ggT6zm49rJ+apA5/hYVumWrUZ36v1vXYLu3wdkm1uBHGKRhn/O0Fe4U6UnR9B2jwbVAzu9QQvQPKc+dsYHe2LfXaZdYGd9T+9RbOGSyZvSMNiZKW2nmhOVMmUyKfJi3zFjYghsL5Ci2NrPjF4OHLakSRuPdmAyltPl1F0lHoGVb8PoqPh9ylEP785PJ9po+ZhC+ig9EL2SjlZCA7h6yBl12OlKtSKJ13YRK2Msw9Wh15hYLWjF0gz5cyhFPbUY6qfEJTMXHwphUTlITpwAtKfeyly1GlaPeLZEu/RGPbo74l8KTYBsZEETIlXLu24r2T1wWbdHb6o6sC691cr6es9bZUxFfgb44DxhUMokx5bitAeNE06xavJl6TtPga3EzlBa4XTbXkwlXd9hcvAJUbUXHde1umSxnT9oZXGPyHrNjfN/l56TRsqt4cWxYFYecbVEEaN0N1pCXoYjdkhCPcejS7ot4psmXyR+g2O8Oc0u/GQlUfM6mCkn3Hjs+Hu5QvphP27mvvf27ET/81wtbZjY36Dve75ZJpm9th9Rgon5xP5Rx3WYvdD62jhClr4AZBZokLQum428r6IMCg4RrzPNA9pizv6JmvsUFYfHBEoq3TdeCyHreIvSkyU4L3s3l7fBuqqyvk=
  - secure: YNLzoLNyxj5Jnerv3vM228mCG3E1Gv/63xSAHWR5CEP99N9k3tWYGGW3iWivzuSvCM41ofuSNfx63AiTmKCC2wume3hvdJW9VjUWPZ6NxLA1Gx86gx3xKNwpqbSesJWYSPu3QtTWs9DowjwkWpP1H6ShyXJW1/Onw9r7mQiQqUbwVW2ZAdBFphTd/G64gZjN3p1bUmH4CSpjoNbAibiylo+fSH7Ebs37daXuNfdCqlQF14A/6o32oP1AZP8tf6ef6HSQY+bQXZkhpwmV5cLz72/BG2ijXvz2rt/ySqyXWLwW3e3k/bBmYTGLpZ4zHJo4XY7y1DcYqDp+YFMTdvgqxzZx77xfX9E2YW/s3mO5Zbi6hjGQ3O551l3mucHuGjXWYA6Yekd6pTqkdQYDUvfd41N/Cj62i4hUK83KomEw3cwuN6pCEHmCjvfTngRRFMcnwRUc+2nOwcAWaXdys+pQCkJ1ZBJi4AF7WzePrTpreWX1GIdBy1rhNGcI258yXKT+mjKtUKSDhIW53oKFcsGxLPuKc2I3bg7Nu+ShwDXdM3M9/dt5kFu8QZMqjW8X1tQNBrEV0XvmRwgXRtbqxvkCgM38PIkIzPml/bcpJJ8lze/UHhACStLnjLND7YiSw8LKORPKiH7PkiEHYffEBb2CDAhLWQDdDdVG8WNiNAIw1iM=
  - secure: OxaRXv5dPAHwvPBc1UgJvSWCgewQ6ZRQ0xH9WcCcSa0dMbMjRE9PyTNoLq3wF7lt6wzcADBqBhMLi+h09WdTFBMshAI6xaymguGmB4Im8iEIHf4BXaVQf53QFLEm2xXSspouhHktMctsGPnBxmxofiZ3er0cIN4BFozRl4WMh8neT/W8X/O/dypIhUNurynjQqgkFRJBhFHmyOiwK4JnwbzowM8gij70fRDDFCZ9SebOGdYp4nhQVS8qACjPWB0I5wYfPSD+3DSjJLuszvRvOivKMP6od31GP8bVr0mTn+1j4tSHLsi95458ZlNYOlOFhocCTneHtHKHGWK0qSeFSjLUgewBM8zPkWlJZtOF/swPzihCG4UNEIZyIw+/gU654Sw6OKJjrCakQeMiwXtgAVihvDgY9WzgqonWziyHcAxxT1YIZcn+Ij8TUSlIb7IY4tGbJpmPEsV6fT8TJM+zvv7PuDzyRrlzNVRlMlYKmqDo64ktaWfqFCCxikr+wMpsQWcNp769WBylr+nFrx/NKmAEz3fc3DyQG43QnrNiELHlqLcJtcixKR+B5DS6aZl6yYOak49SynEVDnsJFuAXb2Kw+kGu5+QV5Q31wCfyL0DHpREYelFn62v6guY9I/bNwnhn0erVX1ZLpouDBVfHw0LOScV3akcwvjPdGQOn5zM=
git:
  submodules: false
stages:
- name: develop
  if: branch =~ ^develop/.*$
- name: master
  if: branch = master
jobs:
  include:
  - stage: develop
    name: Develop Job
    cache:
      cocoapods: true
      directories:
      - Carthage
    before_script:
    - "./scripts/add-key.sh"
    before_install:
    - openssl aes-256-cbc -K $encrypted_f271659ba74d_key -iv $encrypted_f271659ba74d_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    install:
    - gem install bundler -v 2.0.1
    - bundle install
    script:
    - fastlane dependencies
    - fastlane build_ipa
    after_script:
    - "./scripts/remove-key.sh"
    - "./scripts/write_homebrew_to_cache.sh mockturtle"
    deploy:
    - provider: script
      skip_cleanup: true
      script: fastlane deploy_develop
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^develop\\/.*$"
  - stage: master
    name: Master Job
    before_script:
    - "./scripts/add-key.sh"
    install:
    - gem install bundler -v 2.0.1
    - bundle install
    script:
    - fastlane resign_current_version_from_s3_bucket
    after_script:
    - "./scripts/remove-key.sh"
    deploy:
    - provider: script
      skip_cleanup: true
      script: fastlane deploy_master
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH = master"
