fastlane_version "2.57.0"
default_platform :ios

platform :ios do

  desc "Installs dependencies"
  lane :dependencies do
    sh "pod install --repo-update"
    sh "cd .. && carthage bootstrap --platform iOS --cache-builds"
  end

  desc "Build ipa"
  lane :build_ipa do
    # update build number from travis env
    build_number = ENV["TRAVIS_BUILD_NUMBER"]
    build_number ||= 1
    set_info_plist_value(path: "./JPPerformance/Info.plist",
                         key: "CFBundleVersion",
                         value: "#{build_number}")

    build_app(
      scheme: "JPPerformance",
      workspace: "JPPerformance.xcworkspace",
      clean: true,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "com.pageler.christoph.JPPerformance" => "JP Performance AdHoc",
        }
      },
      output_directory: "build",
      output_name: "JPPerformance.ipa"
    )
  end

  desc "Create App Store Screenshots"
  lane :screenshots do
    snapshot(
      workspace: 'JPPerformance.xcworkspace',
      scheme: 'JPPerformanceUITests',
      devices: [
        'iPhone 5s',
        'iPhone 8',
        'iPhone 8 Plus',
        'iPhone Xs',
        'iPhone Xs Max'
      ],
      languages: [
        "en-US",
        "de-DE"
      ],
      output_simulator_logs: false,
      concurrent_simulators: false
      # clear_previous_screenshots: true
    )
  end

  desc "Deploys App to AppCenter"
  lane :deploy_develop do
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: "christoph.pageler",
      app_name: "JP-Fan-App",

      file: "./build/JPPerformance.ipa",
      dsym: "./build/JPPerformance.app.dSYM.zip",

      destinations: "Collaborators"
    )
  end

  desc "Deploys App to AppStore"
  lane :deploy_master do
    puts "implement deploy master"
  end

end
